---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels: {{ include "prefect.labels" . | nindent 4 }}
    app.kubernetes.io/component: hasura
spec:
  type: ClusterIP
  ports:
    - name: hasura
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector: {{ include "prefect.labels" . | nindent 4 }}
    app.kubernetes.io/component: hasura

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prefect.fullname" . }}-db
  labels: {{ include "prefect.labels" . | nindent 4 }}
    app.kubernetes.io/component: hasura
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "prefect.labels" . | nindent 6 }}
      app.kubernetes.io/component: hasura
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "prefect.labels" . | nindent 8 }}
        app.kubernetes.io/component: hasura
    spec:
      containers:
        - name: {{ template "prefect.fullname" . }}-hasura
          image: "{{ .Values.hasura.image.repository }}:{{ .Values.hasura.image.tag }}"
          imagePullPolicy: {{ .Values.hasura.image.pullPolicy }}
          ports:
            - name: hasura
              containerPort: 3000
              protocol: TCP
          resources: {{ toYaml .Values.hasura.resources | nindent 12 }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "prefect.fullname" . }}-secrets
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "prefect.fullname" . }}-secrets
                  key: db_password
            - name: POSTGRES_DB
              value: {{ .Values.db.database }}
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/{{ .Values.db.database }}"
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_SERVER_PORT
              value: "3000"
            - name: HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE
              value: "100"
      restartPolicy: Always
      nodeSelector: {{ toYaml .Values.hasura.nodeSelector | nindent 8 }}
      affinity:     {{ toYaml .Values.hasura.affinity     | nindent 8 }}
      tolerations:  {{ toYaml .Values.hasura.tolerations  | nindent 8 }}
