apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prefect.fullname" . }}-secrets
  labels: {{ include "prefect.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  db_username: {{ .Values.db.username | quote }}
  db_password: {{ .Values.db.password | quote }}
